# k3d cluster configuration
apiVersion: k3d.io/v1alpha5

kind: Simple
metadata:
  name: my-cluster

image: rancher/k3s:v1.32.3-k3s1
ports:
  - port: 30008:30008
    nodeFilters:
      - server:0
  - port: 8888:30007
    nodeFilters:
      - server:0
  - port: 80:80 #NOTE: loadbalancer
    nodeFilters:
      - loadbalancer
  - port: 22:22 #NOTE: ssh
    nodeFilters:
      - loadbalancer

# Cluster settings
servers: 1
