# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   # vb.gui = true
    vb.linked_clone = true
  end

  # config.vm.boot_timeout = 600

  config.vm.define "atouatiS_2" do |server|
    server.vm.box = "mynixos"
    server.vm.hostname = "atouatiS"
    # server.vm.provision :nixos, run: 'always', path: "confs/networkS.nix"
    server.vm.provision "shell", inline: <<-SHELL
      echo "Updating hostname to atouaiS"
      sudo echo "atouatiS\n127.0.0.1 app1.com\n127.0.0.1 app2.com\n127.0.0.1 app3.com" > /etc/hostname
      sudo hostname "atouatiS"
      SHELL
    server.vm.network "private_network", ip: "192.168.56.110"
    # server.vm.network "public_network", ip: "192.168.56.110", bridge: "wlp108s0"
    server.vm.provision :nixos, run: 'always', path: "confs/server.nix"
    server.vm.synced_folder "scripts/", "/vagrant/scripts", type: "rsync"
    server.vm.provision "shell", inline: <<-SHELL
      sudo chmod +x /vagrant/scripts/3apps.sh
      sudo /vagrant/scripts/3apps.sh
      SHELL
  end

  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080


  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  #NOTE: but because we built this one locally...
  # config.vm.box_check_update = false
end
