apiVersion: v1
kind: Service
metadata:
  name: wil42
spec:
  type: NodePort
  selector:
    app: wil42
  ports:
    - port: 8888
      nodePort: 30007

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42
  template:
    metadata:
      labels:
        app: wil42
    spec:
      containers:
      - name: wil42
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
