# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   # vb.gui = true
    vb.linked_clone = true
    #ISSUE: suspecting that this version and configuration of nix does not play well with memory
    # vb.memory = 1024
    # vb.cpus = 1
  end

  # config.vm.boot_timeout = 600

  config.vm.define "atouatiS" do |server|
    server.vm.box = "mynixos"
    server.vm.hostname = "atouatiS"
    # server.vm.provision :nixos, run: 'always', path: "confs/networkS.nix"
    server.vm.provision "shell", inline: <<-SHELL
      echo "Updating hostname to atouaiS"
      sudo echo "atouatiS" > /etc/hostname
      sudo cat /vagrant/scripts/usefulrc > /root/.bashrc
      SHELL
    server.vm.network "private_network", ip: "192.168.56.110", interface: 1
    server.vm.provision :nixos, run: 'always', path: "confs/server.nix"
    # server.vm.provision "shell", inline: <<-SHELL
    #   sudo nixos-rebuild switch
    #   SHELL
    #
  end

  # Define second machine (ServerWorker)
  # config.vm.define "atouatiSW" do |worker|
  #   worker.vm.box = "mynixos"
  #   worker.vm.hostname = "atouatiSW"
  #   worker.vm.network "private_network", ip: "192.168.56.111"
  #
  #   worker.vm.synced_folder "scripts/", "/vagrant/scripts", type: "rsync"
  #   worker.vm.provision :nixos, run: 'always', path: "confs/worker.nix"
  #
  #   worker.vm.provision "shell", inline: <<-SHELL
  #     echo "Updating hostname to $atouatiSW"
  #     sudo hostname "atouatiSW"
  #     sudo chmod +x /vagrant/scripts/merge-k3s-kubectl.sh
  #     sudo /vagrant/scripts/merge-k3s-kubectl.sh
  #     SHELL
  # end



  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080


  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  #NOTE: but because we built this one locally...
  # config.vm.box_check_update = false
end
